mqtt:
    broker: 192.168.34.118
    port: 1883
    username:
    password:
        tls:
            ca-certs: 
            certfile:
            keyfile:
            insecure-tls:

waves:
  - name: "basement-radon"
    addr: 98:07:2d:43:4d:8e
